### ISSUE TITLE
When Anchor Button is turned on, Application will not Allow me to shrink the window size. In other words, the window stays maximized.

### ISSUE THREAD

**Issue by A-Chidalu** [lukas-rose-216489023/EECS2311Project#2]
# Group 17 VennApplication Bug Report 1

### Summary: When Anchor Button is turned on, Application will not Allow me to shrink the window size. In other words, the window stays maximized.

Product: VennApplication [Group 17]

Version: Midterm Project Submission Release [Released on February 23rd, 2020]

Component: Anchor Button

Platform: 
-Processor: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz 1.99Ghz
-RAM: 16GB
-System Type: 64-bit Operating System, x64-based processor

OS: Windows 10 Home

Severity: Major

Priority: P2 (Second-Most Important)

Full Description:

	Steps To Reproduce: 
		1. Open VennApplication using java -jar VennApplication
		2. In the top right corner of the screen, turn on Anchoring
		3. Try to "Restore Down" The application by clicking the Button to the left of the X sign in the top right corner of the window
		4. Notice as the application snaps back into place after trying to Decrease the window size, Not allowing the user to decerase the window size

	Acutal Results: The window kept on snapping back to mazimized form and would not decrease in size
	
	Expected Results: Expected the window to allow me to decrease the size and increase the size

	Build & Date: VennApplication Release 1, encounterd on March 14th, 2020

**Comment by A-Chidalu** [comment]
# Group 17 Bug VennApplication Bug Report 2

### Summary: ArrayIndex Out of Bounds Exception Thrown in Console when trying to "Delete Selected Text From list" in the "Add Multiple tex box" section.

Product: VennApplication [Group 17]

Version: Midterm Project Submission Release [Released on February 23rd, 2020]

Component: Anchor Button

Platform: 
-Processor: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz 1.99Ghz
-RAM: 16GB
-System Type: 64-bit Operating System, x64-based processor

OS: Windows 10 Home

Severity: Minor (Exception Can be Easily Caught and a warning popup can be thrown)

Priority: P3 (Normal Priority)

Full Description:

	Steps To Reproduce: 
		1. Open VennApplication using java -jar VennApplication
		2. In the top left corner of the screen click the "Add Multiple New Text Boxes" Button
		3. Without Entering Any text, Click the "Delete Selected Text from List" Button
		4. Notice as an exception stack trace pops up

	Acutal Results: An Exception stack trace appeared in my console
	
	Expected Results: Expected A warning saying, "There must be text to delete!" or something similar. Or even nothing. 

	Build & Date: VennApplication Release 1, encounterd on March 14th, 2020


## Photo of the Exception
![image](https://user-images.githubusercontent.com/50505942/76693672-88a97080-663f-11ea-9c5c-99853d81ef87.png)

**Comment by Ahmed-Jawad-216340309** [comment]
This is the expected result as indicated in the UM.
