### ISSUE TITLE
ArrayIndex Out of Bounds Exception Thrown in Console when trying to "Delete Selected Text From list" in the "Add Multiple text box" section.

### ISSUE THREAD

**Issue by A-Chidalu** [lukas-rose-216489023/EECS2311Project#3]
# Group 17 VennApplication Bug Report 2

### Summary: ArrayIndex Out of Bounds Exception Thrown in Console when trying to "Delete Selected Text From list" in the "Add Multiple text box" section.

Product: VennApplication [Group 17]

Version: Midterm Project Submission Release [Released on February 23rd, 2020]

Component: Add Multiple New Text Boxes Button

Platform: 
-Processor: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz 1.99Ghz
-RAM: 16GB
-System Type: 64-bit Operating System, x64-based processor

OS: Windows 10 Home

Severity: Minor (Exception Can be Easily Caught and a warning popup can be thrown)

Priority: P3 (Normal Priority)

Full Description:

	Steps To Reproduce: 
		1. Open VennApplication using java -jar VennApplication
		2. In the top left corner of the screen click the "Add Multiple New Text Boxes" Button
		3. Without Entering Any text, Click the "Delete Selected Text from List" Button
		4. Notice as an exception stack trace pops up

	Acutal Results: An Exception stack trace appeared in my console
	
	Expected Results: Expected A warning saying, "There must be text to delete!" or something similar. Or even nothing. 

	Build & Date: VennApplication Release 1, encounterd on March 14th, 2020

## Photo of Exception

![image](https://user-images.githubusercontent.com/50505942/76693684-c7d7c180-663f-11ea-87d2-be39e67f7f98.png)

**Comment by Ahmed-Jawad-216340309** [comment]
The front-end (GUI) works as expected so, won't fix.
