### ISSUE TITLE
"Take a ScreenShot of VennDiagram!" Button does not provide me with a screenshot

### ISSUE THREAD

**Issue by A-Chidalu** [lukas-rose-216489023/EECS2311Project#4]
# Group 17 VennApplication Bug Report 3

### Summary: "Take a ScreenShot of VennDiagram!" Button does not provide me with a screenshot

Product: VennApplication [Group 17]

Version: Midterm Project Submission Release [Released on February 23rd, 2020]

Component: "Take a ScreenShot of Venn Diagram!" Button

Platform: 
-Processor: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz 1.99Ghz
-RAM: 16GB
-System Type: 64-bit Operating System, x64-based processor

OS: Windows 10 Home

Severity: Minor 

Priority: P3 (Normal Priority)

Full Description:

	Steps To Reproduce: 
		1. Open VennApplication using java -jar VennApplication
		2. In the bottom left corner of the screen click the "Take a ScreenShot of VennDiagram!" Button
		3. Notice as nothing happens

	Acutal Results: Nothing happens
	
	Expected Results: A Screenshot of the Application to be downloaded

	Build & Date: VennApplication Release 1, encounterd on March 14th, 2020

**Comment by Ahmed-Jawad-216340309** [comment]
The screenshot should be in the same directory as the .jar file.
