### ISSUE TITLE
Screen shot does not provide a paste-able image

### ISSUE THREAD

**Issue by hassanmuk** [lukas-rose-216489023/EECS2311Project#5]
**OS:** macOS Mojave: Version 10.14.4
**Release Tested:** Midterm project submission
**Java Version:** 11.0.3
**Description:** The print screen button does not provide a paste-able image
**Steps to reproduce:**
     1. Click the "Take Screenshot of Venn Diagram!" button on the bottom left
**Expected Results:** A paste-able image of the Venn-Diagram in the state it was when the button was clicked
**Actual Results:** No paste-able image is made

**Comment by Ahmed-Jawad-216340309** [comment]
The expected result is a png image file being created in the current directory (where the application was launched).
