### ISSUE TITLE
Application cannot be resized

### ISSUE THREAD

**Issue by hassanmuk** [lukas-rose-216489023/EECS2311Project#6]
**OS:** macOS Mojave: Version 10.14.4
**Release Tested:** Midterm project submission
**Java Version:** 11.0.3
**Description:** The application window is not resize-able, it just goes back to fullscreen if anything is touched
**Steps to reproduce:**
     1. Resize the application window by using the resize button at the top right or drag the window 
        smaller
     2. Click anywhere on the application screen
**Expected Results:** The window stays in the resized position
**Actual Results:** The window automatically goes back to fullscreen when touched

**Comment by Ahmed-Jawad-216340309** [comment]
This sounds like the expected output if 'anchoring' was toggled on. Are you sure the anchoring was toggled off?
