### ISSUE TITLE
Unresizable window

### ISSUE THREAD

**Issue by sidoverflow** [lukas-rose-216489023/EECS2311Project#9]
##
**OS**: *CentOS Linux release 7.7.1908 (Core)*
**Processor**: *Intel(R) Core(TM) i7-8700T CPU @ 2.40GHz*
**RAM**: *16GB*
**Priority**: *Low*
**Release**: *vM*
**Java Version**: *1.8.0_202*
##
## Description
The application window cannot be resized when *anchoring* is toggled. The window snaps back to the original size on attempting to resize.

## Steps to Reproduce

1. Toggle *Anchoring* to ***on***
2. Resize window

## Expected Result
A resized window of the application according to the user's needs.

## Actual Result
The application window resets to the original size.

**Comment by Ahmed-Jawad-216340309** [comment]
This is the expected result as indicated by the UM.
